# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6831b5d631d5a862b88f089c5f61242db758ea4aec1c6ab8eab64550f90a0341fb95a15a8e8f168b39c158a1780596a51f097f7aebe9512712fe2ceaa04ef2ee

test:
  secret_key_base: 0c8b81bbbc6d91fd41031f2e43929ef53c069057ea5e9e9eb71593af9a26d9b0d984b37b673708b99aade6ec2c8a4eab7b0ae02e8d14b570dcddb14dd53c32f9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
